printWidth: 120
tabWidth: 2
useTabs: false
semi: false
singleQuote: true
quoteProps: as-needed
trailingComma: es5
bracketSpacing: true
arrowParens: always
endOfLine: lf
proseWrap: preserve
insertFinalNewline: true
overrides:
  - files: '*.json'
    options:
      parser: json
  - files: '*.jsonc'
    options:
      parser: jsonc
      trailingComma: none
  - files:
      - '*.yaml'
      - '*.yml'
    options:
      parser: yaml
      tabWidth: 2
  - files: '*.md'
    options:
      parser: markdown
      proseWrap: preserve
