# 自定义验证错误信息不包含验证预期内容（即用户输入内容）, 而是以更加友好的形式展现错误。
# - 受支持字段参考: https://github.com/pydantic/pydantic-core/blob/a5cb7382643415b716b1a7a5392914e50f726528/tests/test_errors.py#L266
# - 替换方式参考: https://github.com/pydantic/pydantic/blob/caa78016433ec9b16a973f92f187a7b6bfde6cb5/docs/errors/errors.md?plain=1#L232


VALIDATION_ERROR_MESSAGES = {
    'no_such_attribute': "对象不存在属性 '{attribute}'",
    'json_invalid': 'JSON 数据解析失败',
    'json_type': 'JSON 输入应该是字符串、字节或字节数组',
    'recursion_loop': '递归错误 - 检测到循环引用',
    'model_type': '输入应该是有效的字典或 {class_name} 实例',
    'model_attributes_type': '输入应该是有效的字典或对象以提取字段',
    'dataclass_exact_type': '输入应该是 {class_name} 的实例',
    'dataclass_type': '输入应该是字典或 {class_name} 的实例',
    'missing': '字段必填',
    'frozen_field': '字段已冻结',
    'frozen_instance': '实例已冻结',
    'extra_forbidden': '不允许额外的输入',
    'invalid_key': '键应该是字符串',
    'get_attribute_error': '提取属性错误: {error}',
    'none_required': '输入应该为 None',
    'enum': '输入应该是 {expected}',
    'greater_than': '输入应该大于 {gt}',
    'greater_than_equal': '输入应该大于或等于 {ge}',
    'less_than': '输入应该小于 {lt}',
    'less_than_equal': '输入应该小于或等于 {le}',
    'finite_number': '输入应该是有限数字',
    'too_short': '{field_type} 应该至少有 {min_length} 项, 而不是 {actual_length}',
    'too_long': '{field_type} 应该最多有 {max_length} 项, 而不是 {actual_length}',
    'string_type': '输入应该是有效的字符串',
    'string_sub_type': '输入应该是字符串, 而不是 str 的子类实例',
    'string_unicode': '输入应该是有效的字符串, 无法将原始数据解析为 Unicode 字符串',
    'string_pattern_mismatch': "字符串应该匹配模式 '{pattern}'",
    'string_too_short': '字符串应该至少有 {min_length} 个字符',
    'string_too_long': '字符串应该最多有 {max_length} 个字符',
    'dict_type': '输入应该是有效的字典',
    'mapping_type': '输入应该是有效的映射, 错误: {error}',
    'iterable_type': '输入应该是可迭代的',
    'iteration_error': '迭代对象错误: {error}',
    'list_type': '输入应该是有效的列表',
    'tuple_type': '输入应该是有效的元组',
    'set_type': '输入应该是有效的集合',
    'bool_type': '输入应该是有效的布尔值',
    'bool_parsing': '输入应该是有效的布尔值, 无法解释输入',
    'int_type': '输入应该是有效的整数',
    'int_parsing': '输入应该是有效的整数, 无法将字符串解析为整数',
    'int_parsing_size': '无法将输入字符串解析为整数, 超过了最大大小',
    'int_from_float': '输入应该是有效的整数, 得到一个带有小数部分的数字',
    'multiple_of': '输入应该是 {multiple_of} 的倍数',
    'float_type': '输入应该是有效的数字',
    'float_parsing': '输入应该是有效的数字, 无法将字符串解析为数字',
    'bytes_type': '输入应该是有效的字节',
    'bytes_too_short': '数据应该至少有 {min_length} 字节',
    'bytes_too_long': '数据应该最多有 {max_length} 字节',
    'value_error': '字段值错误: {error}',
    'assertion_error': '断言失败: {error}',
    'literal_error': '输入应该是 {expected}',
    'date_type': '输入应该是有效的日期',
    'date_parsing': '输入应该是有效的日期格式 YYYY-MM-DD, {error}',
    'date_from_datetime_parsing': '输入应该是有效的日期或日期时间, {error}',
    'date_from_datetime_inexact': '提供给日期的日期时间应该有零时间 - 即应该是准确的日期',
    'date_past': '日期应该在过去',
    'date_future': '日期应该在将来',
    'time_type': '输入应该是有效的时间',
    'time_parsing': '输入应该是有效的时间格式, {error}',
    'datetime_type': '输入应该是有效的日期时间',
    'datetime_parsing': '输入应该是有效的日期时间, {error}',
    'datetime_object_invalid': '无效的日期时间对象, 得到 {error}',
    'datetime_past': '输入应该在过去',
    'datetime_future': '输入应该在将来',
    'timezone_naive': '输入不应该有时区信息',
    'timezone_aware': '输入应该有时区信息',
    'timezone_offset': '需要时区偏移 {tz_expected}, 得到 {tz_actual}',
    'time_delta_type': '输入应该是有效的时间差',
    'time_delta_parsing': '输入应该是有效的时间差, {error}',
    'frozen_set_type': '输入应该是有效的冻结集合',
    'is_instance_of': '输入应该是 {class} 的实例',
    'is_subclass_of': '输入应该是 {class} 的子类',
    'callable_type': '输入应该是可调用的',
    'union_tag_invalid': "使用 {discriminator} 找到的输入标签 '{tag}' 与预期的任何标签不匹配: {expected_tags}",
    'union_tag_not_found': '无法使用判别器 {discriminator} 提取标签',
    'arguments_type': '参数必须是元组、列表或字典',
    'missing_argument': '缺少必需的参数',
    'unexpected_keyword_argument': '意外的关键字参数',
    'missing_keyword_only_argument': '缺少必需的仅关键字参数',
    'unexpected_positional_argument': '意外的位置参数',
    'missing_positional_only_argument': '缺少必需的仅位置参数',
    'multiple_argument_values': '参数获得了多个值',
    'url_type': 'URL 输入应该是字符串或 URL',
    'url_parsing': '输入应该是有效的 URL, {error}',
    'url_syntax_violation': '输入违反了严格的 URL 语法规则, {error}',
    'url_too_long': 'URL 应该最多有 {max_length} 个字符',
    'url_scheme': 'URL 方案应该是 {expected_schemes}',
    'uuid_type': 'UUID 输入应该是字符串、字节或 UUID 对象',
    'uuid_parsing': '输入应该是有效的 UUID, {error}',
    'uuid_version': '需要 UUID 版本 {expected_version}',
    'decimal_type': '十进制输入应该是整数、浮点数、字符串或十进制对象',
    'decimal_parsing': '输入应该是有效的十进制数',
    'decimal_max_digits': '十进制输入的总位数不应超过 {max_digits}',
    'decimal_max_places': '十进制输入的小数位数不应超过 {decimal_places}',
    'decimal_whole_digits': '十进制输入小数点前的位数不应超过 {whole_digits}',
}


# https://github.com/pydantic/pydantic/blob/caa78016433ec9b16a973f92f187a7b6bfde6cb5/docs/errors/usage_errors.md
USAGE_ERROR_MESSAGES = {
    'class-not-fully-defined': '类未完全定义',
    'custom-json-schema': '自定义 JSON Schema 错误',
    'decorator-missing-field': '装饰器应用在了不存在的字段',
    'discriminator-no-field': '字段未在模型中定义',
    'discriminator-alias-type': '字段的别名应该是字符串',
    'discriminator-needs-literal': '字段应该是 Literal 类型',
    'discriminator-alias': '字段定义了不同的别名',
    'discriminator-validator': '字段不允许使用 before、wrap 或 plain 验证器',
    'typed-dict-version': '在 Python < 3.12 上应该使用 typing_extensions.TypedDict 而不是 typing.TypedDict',
    'model-field-overridden': '基类中定义的字段被非注解的属性覆盖',
    'model-field-missing-annotation': '字段缺少类型注解',
    'config-both': 'Config 和 model_config 不能同时定义',
    'removed-kwargs': '关键字参数在 Pydantic V2 中已被移除',
    'invalid-for-json-schema': '无法为类型生成 JSON Schema',
    'json-schema-already-used': 'JSON Schema 生成器已被使用',
    'base-model-instantiated': '不能直接实例化 BaseModel',
    'undefined-annotation': '未定义的类型注解',
    'schema-for-unknown-type': '无法为未知类型生成 CoreSchema',
    'import-error': '导入了在 Pydantic V2 中不可用的对象',
    'create-model-field-definitions': 'create_model 的字段定义无效',
    'create-model-config-base': 'create_model 中不能同时使用 __config__ 和 __base__',
    'validator-no-fields': '必须指定字段',
    'validator-invalid-fields': '字段应该是字符串参数而不是列表',
    'validator-instance-method': '应该是类方法而不是实例方法',
    'root-validator-pre-skip': '必须指定 skip_on_failure=True',
    'model-serializer-instance-method': 'model_serializer 必须应用于实例方法',
    'validator-v1-signature': 'Pydantic V1 风格的验证器签名不支持',
    'validator-signature': '签名不正确',
    'field-serializer-signature': 'field_serializer 的签名不正确',
    'model-serializer-signature': 'model_serializer 的签名不正确',
    'multiple-field-serializers': '定义了多个 model_serializer',
    'invalid_annotated_type': '无法注解类型',
    'type-adapter-config-unused': 'TypeAdapter 不能传递 config 参数',
    'root-model-extra': "不能在 RootModel 上指定 model_config['extra']",
}
