"""新增菜单表, 角色菜单关联表

Revision ID: 6e3c3f509739
Revises: 29a20b69a879
Create Date: 2025-12-18 13:35:16.527807+08:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import backend.common.model


# revision identifiers, used by Alembic.
revision: str = '6e3c3f509739'
down_revision: str | None = '29a20b69a879'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """应用迁移（升级数据库结构）"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'sys_menu',
        sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键 ID'),
        sa.Column('title', sa.String(length=50), nullable=False, comment='菜单标题'),
        sa.Column('type', sa.Integer(), nullable=False, comment='菜单类型'),
        sa.Column('path', sa.String(length=200), nullable=True, comment='访问地址、外链地址'),
        sa.Column('component', sa.String(length=300), nullable=True, comment='组件的文件路径'),
        sa.Column('permission', sa.String(length=128), nullable=True, comment='权限标识'),
        sa.Column('icon', sa.String(length=50), nullable=True, comment='图标'),
        sa.Column('redirect', sa.String(length=200), nullable=True, comment='重定向访问地址'),
        sa.Column('active_menu', sa.String(length=200), nullable=True, comment='访问时，应该高亮的菜单'),
        sa.Column('status', sa.Integer(), server_default='1', nullable=False, comment='状态(0停用 1正常)'),
        sa.Column('hidden', sa.Boolean(), server_default='false', nullable=False, comment='是否隐藏菜单'),
        sa.Column('keep_alive', sa.Boolean(), server_default='false', nullable=False, comment='是否缓存该页面'),
        sa.Column('tab', sa.Boolean(), server_default='true', nullable=False, comment='是否在标签页显示'),
        sa.Column('breadcrumb', sa.Boolean(), server_default='true', nullable=False, comment='是否在面包屑中显示'),
        sa.Column('sort', sa.Integer(), nullable=False, comment='排序'),
        sa.Column('remark', sa.String(length=500), nullable=True, comment='备注'),
        sa.Column('parent_id', sa.BigInteger(), nullable=True, comment='父菜单 ID'),
        sa.Column('created_time', sa.DateTime(timezone=True), nullable=False, comment='创建时间'),
        sa.Column('updated_time', sa.DateTime(timezone=True), nullable=True, comment='更新时间'),
        sa.ForeignKeyConstraint(['parent_id'], ['sys_menu.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        comment='菜单信息表',
    )
    op.create_index(op.f('ix_sys_menu_id'), 'sys_menu', ['id'], unique=True)
    op.create_index(op.f('ix_sys_menu_parent_id'), 'sys_menu', ['parent_id'], unique=False)
    op.create_index(op.f('ix_sys_menu_status'), 'sys_menu', ['status'], unique=False)
    op.create_table(
        'sys_role_menu',
        sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键 ID'),
        sa.Column('role_id', sa.BigInteger(), nullable=False, comment='角色 ID'),
        sa.Column('menu_id', sa.BigInteger(), nullable=False, comment='菜单 ID'),
        sa.ForeignKeyConstraint(['menu_id'], ['sys_menu.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['role_id'], ['sys_role.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('role_id', 'menu_id', name='uq_role_menu'),
    )
    op.create_index(op.f('ix_sys_role_menu_menu_id'), 'sys_role_menu', ['menu_id'], unique=False)
    op.create_index(op.f('ix_sys_role_menu_role_id'), 'sys_role_menu', ['role_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """回滚迁移（降级数据库结构）"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sys_role_menu_role_id'), table_name='sys_role_menu')
    op.drop_index(op.f('ix_sys_role_menu_menu_id'), table_name='sys_role_menu')
    op.drop_table('sys_role_menu')
    op.drop_index(op.f('ix_sys_menu_status'), table_name='sys_menu')
    op.drop_index(op.f('ix_sys_menu_parent_id'), table_name='sys_menu')
    op.drop_index(op.f('ix_sys_menu_id'), table_name='sys_menu')
    op.drop_table('sys_menu')
    # ### end Alembic commands ###
