"""新增 SysUser 表

Revision ID: 204745561d1e
Revises:
Create Date: 2025-12-17 16:34:37.731863+08:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import backend.common.model


# revision identifiers, used by Alembic.
revision: str = '204745561d1e'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """应用迁移（升级数据库结构）"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'sys_user',
        sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键 ID'),
        sa.Column('username', sa.String(length=20), nullable=False, comment='用户名'),
        sa.Column('password', sa.String(length=255), nullable=True, comment='密码'),
        sa.Column('salt', sa.LargeBinary(length=255), nullable=True, comment='加密盐'),
        sa.Column('nickname', sa.String(length=20), nullable=False, comment='昵称'),
        sa.Column('realname', sa.String(length=50), nullable=True, comment=' 真实姓名'),
        sa.Column('email', sa.String(length=50), nullable=True, comment='邮箱'),
        sa.Column('phone', sa.String(length=11), nullable=True, comment='手机号'),
        sa.Column('avatar', sa.String(length=500), nullable=True, comment='头像'),
        sa.Column('gender', sa.Integer(), nullable=True, comment='性别(0女 1男 3其他)'),
        sa.Column('birth_date', sa.DateTime(timezone=True), nullable=True, comment='出生日期'),
        sa.Column('user_type', sa.String(length=3), server_default='00', nullable=False, comment='用户类型'),
        sa.Column('status', sa.Integer(), server_default='1', nullable=False, comment='账号状态(0停用 1正常)'),
        sa.Column('is_multi_login', sa.Boolean(), server_default='false', nullable=False, comment='是否允许多端登录'),
        sa.Column('is_superuser', sa.Boolean(), server_default='false', nullable=False, comment='是否是超级管理员'),
        sa.Column('is_admin', sa.Boolean(), server_default='false', nullable=False, comment='是否是后台管理员'),
        sa.Column('is_verified', sa.Boolean(), server_default='false', nullable=False, comment='是否实名认证'),
        sa.Column('is_del', sa.Boolean(), server_default='false', nullable=False, comment='是否删除'),
        sa.Column('remark', sa.String(length=500), nullable=True, comment='备注'),
        sa.Column('last_login_ip', sa.String(length=128), nullable=True, comment='最后登录IP'),
        sa.Column('last_login_time', sa.DateTime(timezone=True), nullable=True, comment='最后登录时间'),
        sa.Column('created_time', sa.DateTime(timezone=True), nullable=False, comment='创建时间'),
        sa.Column('updated_time', sa.DateTime(timezone=True), nullable=True, comment='更新时间'),
        sa.PrimaryKeyConstraint('id'),
        comment='用户信息表',
    )
    op.create_index(op.f('ix_sys_user_email'), 'sys_user', ['email'], unique=False)
    op.create_index(op.f('ix_sys_user_id'), 'sys_user', ['id'], unique=True)
    op.create_index(op.f('ix_sys_user_phone'), 'sys_user', ['phone'], unique=True)
    op.create_index(op.f('ix_sys_user_status'), 'sys_user', ['status'], unique=False)
    op.create_index(op.f('ix_sys_user_username'), 'sys_user', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """回滚迁移（降级数据库结构）"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sys_user_username'), table_name='sys_user')
    op.drop_index(op.f('ix_sys_user_status'), table_name='sys_user')
    op.drop_index(op.f('ix_sys_user_phone'), table_name='sys_user')
    op.drop_index(op.f('ix_sys_user_id'), table_name='sys_user')
    op.drop_index(op.f('ix_sys_user_email'), table_name='sys_user')
    op.drop_table('sys_user')
    # ### end Alembic commands ###
