"""新增角色表,用户角色关联表

Revision ID: 29a20b69a879
Revises: 204745561d1e
Create Date: 2025-12-18 10:41:07.725781+08:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import backend.common.model


# revision identifiers, used by Alembic.
revision: str = '29a20b69a879'
down_revision: str | None = '204745561d1e'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """应用迁移（升级数据库结构）"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'sys_role',
        sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键 ID'),
        sa.Column('name', sa.String(length=64), nullable=False, comment='名称'),
        sa.Column('code', sa.String(length=100), nullable=False, comment='权限字符串'),
        sa.Column('status', sa.Integer(), server_default='1', nullable=False, comment='状态（0正常 1停用）'),
        sa.Column('remark', sa.String(length=500), nullable=True, comment='备注'),
        sa.Column('created_time', sa.DateTime(timezone=True), nullable=False, comment='创建时间'),
        sa.Column('updated_time', sa.DateTime(timezone=True), nullable=True, comment='更新时间'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('code'),
        sa.UniqueConstraint('name'),
        comment='角色表',
    )
    op.create_index(op.f('ix_sys_role_id'), 'sys_role', ['id'], unique=True)
    op.create_table(
        'sys_user_role',
        sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键 ID'),
        sa.Column('user_id', sa.BigInteger(), nullable=False, comment='用户 ID'),
        sa.Column('role_id', sa.BigInteger(), nullable=False, comment='角色 ID'),
        sa.ForeignKeyConstraint(['role_id'], ['sys_role.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['user_id'], ['sys_user.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('user_id', 'role_id', name='uq_user_role'),
    )
    op.create_index(op.f('ix_sys_user_role_role_id'), 'sys_user_role', ['role_id'], unique=False)
    op.create_index(op.f('ix_sys_user_role_user_id'), 'sys_user_role', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """回滚迁移（降级数据库结构）"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sys_user_role_user_id'), table_name='sys_user_role')
    op.drop_index(op.f('ix_sys_user_role_role_id'), table_name='sys_user_role')
    op.drop_table('sys_user_role')
    op.drop_index(op.f('ix_sys_role_id'), table_name='sys_role')
    op.drop_table('sys_role')
    # ### end Alembic commands ###
